version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - class-api-network
    volumes:
      - db:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    healthcheck:
      test: [ "CMD", "mongo", "admin", "--eval", "db.serverStatus()" ]
      interval: 30s
      timeout: 10s
      retries: 5

  class-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_TOKEN_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJpc3MiOiJhdXRoMCJ9.AbIJTDMFc7yUa5MhvcP03nJPyCPzZtQcGEp-zWfOkEE
      - TIME_TO_LIVE=60000
      - MONGO_DB=mongodb://root:password@mongodb:27017/classes?authSource=admin
      - ALLOW-ORIGIN=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - class-api-network
    volumes:
      - class-api:/data


volumes:
  class-api: {}
  db: {}

networks:
  class-api-network:
    driver: bridge