spring:
  cache:
    time-to-live: 6000
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/classes?authSource=admin
JWT:
  SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJpc3MiOiJhdXRoMCJ9.AbIJTDMFc7yUa5MhvcP03nJPyCPzZtQcGEp-zWfOkEE